

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
           - Path=/service-a/**
          filters:
            - StripPrefix=1